language: generic
sudo: required
services:
- docker
stages:
  - name: deploy_master
    if: branch = master
  - name: deploy_stage
    if: branch = stage
env:
  global:
  - GIT_SHA=$(git rev-parse HEAD)
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - PORT="5000"
  - PROJECT_ID="multi-k8s-312904"
  - IMAGE_REPO="kulina-app"
  - APP_NAME="dummy-api"
  - REGION="asia-southeast2"
  - PROD_ENV="https://raw.githubusercontent.com/strelok29/environment/master/dummy-api-prod-env.yaml?token=AGFM4PVF7RQHF7T3LOA4HM3AZHGNS"
  - STAGE_ENV="https://raw.githubusercontent.com/strelok29/environment/master/dummy-api-stage-env.yaml?token=AGFM4PUV2EY66ZUOTF5BO3TAZHGQC"
jobs:
  include:
    - stage: deploy_master
      script:
        - openssl aes-256-cbc -K $encrypted_e8b9f665f844_key -iv $encrypted_e8b9f665f844_iv -in ssh.enc -out ssh -d
        - openssl aes-256-cbc -K $encrypted_6330fb5ca1fb_key -iv $encrypted_6330fb5ca1fb_iv -in secret.json.enc -out secret.json -d
        - export SSH_PRIVATE_KEY="$(cat ssh)"
        - curl $PROD_ENV >> env.yaml
        - curl https://sdk.cloud.google.com | bash > /dev/null;
        - source $HOME/google-cloud-sdk/path.bash.inc
        - gcloud components update beta
        - gcloud auth activate-service-account --key-file secret.json
        - gcloud config set project $PROJECT_ID
        - gcloud auth configure-docker
        - docker build -t asia.gcr.io/$PROJECT_ID/$IMAGE_REPO/$APP_NAME:latest
          -t asia.gcr.io/$PROJECT_ID/$IMAGE_REPO/$APP_NAME:$GIT_SHA --build-arg
          SSH_PRIVATE_KEY .
        - docker push asia.gcr.io/$PROJECT_ID/$IMAGE_REPO/$APP_NAME:latest
        - docker push asia.gcr.io/$PROJECT_ID/$IMAGE_REPO/$APP_NAME:$GIT_SHA
        - gcloud run deploy $APP_NAME --port $PORT --region $REGION --allow-unauthenticated --min-instances 1 --image asia.gcr.io/$PROJECT_ID/$IMAGE_REPO/$APP_NAME:$GIT_SHA