language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t strelok2911/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true strelok2911/docker-react npm run test

    


        
        