version : '3'
services :
    web:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - /web/node_modules
            - .:/web

    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /web/node_modules
            - .:/web
        command: ["npm","run","test"]